from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# Register your model with the admin.py
# make and run migrations

# passing in models.Model turns our call into a model so now django understands what it is.
class Product(models.Model):
# A user can have multiple products so we need a 1 to many relationship
# on_delete=models.SET_NULL allow a user to be deleted but their products will not
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    # image =
    brand = models.CharField(max_length=200, null=True, blank=True)
    category = models.CharField(max_length=200, null=True, blank=True)
    description = models.TimeField(null=True, blank=True)
    rating = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    numReviews = models.IntegerField(null=True, blank=True, default=0)
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    countInStock = models.IntegerField(null=True, blank=True, default=0)
    createdAt = models.DateTimeField(auto_now_add=True)
# below sets _id to the autogenerated id that given to newly added projects.
    _id = models.AutoField(primary_key=True, editable=False)


